@ECHO OFF

REM *** MODIFY THE NEXT LINE TO SPECIFY THE LOCATION OF YOUR SCRIPTS ***
SET SCRIPT_DIR= D:\Test
REM *** MODIFY THE NEXT LINE TO SPECIFY THE LOCATION OF YOUR PYTHON.EXE ***
SET PYTHON_BIN=D:\Test\jarvis

PUSHD %SCRIPT_DIR%
%PYTHON_BIN%%*
POPD